### ISSUE TITLE
Remove all manual mapping structs

### ISSUE THREAD

**Issue by Gerrit91** [metal-stack/metal-go#33]
Even if it looks a bit nicer to use for an end-user, I think we should remove all manual wrapper- mapping-functions from this project and users should just use the swagger generated client. Reasons for this are:

- Manual implementation of the mapper functions have errors and they are often hard to find
- Client releases cannot be automated after a new metal-api release (we often miss adequate releases for this repository)
- We are inconsistent with wrapping because we only map requests, users are working with the swagger generated responses though
- All in all, we are actually losing a big advantage of swagger, which automates client generation but we add unnecessary maintenance overhead here

Of course, this requires all clients to update their source code in the end, which is a bit of work.

**Comment by Gerrit91** [comment]
We could do this when we are breaking the go-client anyway when merging https://github.com/metal-stack/metal-api/pull/81

**Comment by majst01** [comment]
Tried to already during network-annotation work, but skipped because of to much hassle. But agree, must be done before reaching v1.0.0

**Comment by majst01** [comment]
Also update to go-swagger 0.2.5

**Comment by Gerrit91** [comment]
First step has been taken: https://github.com/metal-stack/metal-go/pull/75
