### ISSUE TITLE
HMAC auth should not default to Metal-Admin user

### ISSUE THREAD

**Issue by Gerrit91** [metal-stack/metal-go#34]
Some clients do not require admin privileges, but we enforce clients to use it:

https://github.com/metal-stack/metal-go/blob/v0.8.3/metal.go#L74

I think, a user should be able to choose the login user.

**Comment by majst01** [comment]
Its only the description, but still good point !

**Comment by Gerrit91** [comment]
What do you exactly mean by description? The hard-coded sting value for `Metal-Admin` is what goes down into the `Authorization` header for API requests.

**Comment by majst01** [comment]
I didnt now that this is what makes an admin :fearful:
